### PR TITLE
#3 Fix compiler.parser deprecated warning for webpack 2

### LINKED ISSUE #3: compiler.parser is deprecated in webpack 2.

### PR DESCRIPTION
**Pull request by addityasingh**
- Fix compiler.parser deprecated warning when using with Webpack 2
- Fix tests for the plugin callback changes 
- Closes #3

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -39,56 +39,59 @@ ExtractTranslationPlugin.prototype.apply = function(compiler) {
...
+        });
 
-        return false;
+        compilation.dependencyFactories.set(ConstDependency, new NullFactory());
+        compilation.dependencyTemplates.set(ConstDependency, new ConstDependency.Template());
     });
 
     compiler.plugin('done', function() {
         this.done(this.keys);
+        console.log('keys inside plugin', this.keys);
```
Comment (grassator) [inline index.js]: This probably should be removed.

**Comment by grassator** [comment]
I want to do a test run on a real app to make sure that this changes are good, but will do it ASAP. Or alternatively if you have some time to add an integration test that would run whole webpack and check the output this would be awesome.

**Comment by addityasingh** [comment]
@grassator Removed the console.log. Will try for the integration test later today and will let you know if I need help/ run into some issues

**Comment by addityasingh** [comment]
@grassator Please have a look now at the integration test. I got this working with webpack-2 by fixing the scope of `this.functionName`, as the value of `this` was incorrect

File: test/system-test.js [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+const assert = require('assert');
+const fs = require('fs');
+
+describe('Smoke test for the executable script', function() {
+    beforeEach(() => {
+        fs.writeFileSync('test/test-data.js', 'const a = __(\'test.key\');');
+    });
+
+    afterEach(() => {
+        fs.unlinkSync('test/test-data.js');
```
Comment (vigneshshanmugam) [inline test/system-test.js:15]: unnecessary code.. rimraf('test') would have saved some lines. https://github.com/vigneshshanmugam/optimize-js-plugin/blob/master/test/index.js#L51

Comment (addityasingh) [reply test/system-test.js:15]: @vigneshshanmugam  I thought to use rimraf. But just because it was an additional package, i was a little lazy to do that ;)
